vti_encoding:SR|utf8-nl
vti_version:SW|6.0.2.5516
vti_syncwith_localhost\\e\:\\travaux clients\\lentic\\backupsite/e\:/travaux clients/lentic/backupsite:TR|29 Jun 2004 12:26:39 -0000
vti_timelastmodified:TR|29 Jun 2004 12:26:39 -0000
vti_author:SR|2COLT481\\lenticbe
vti_modifiedby:SR|2COLT481\\lenticbe
vti_nexttolasttimemodified:TR|29 Jun 2004 12:26:39 -0000
vti_timecreated:TR|15 Sep 2004 16:56:03 -0000
vti_extenderversion:SR|5.0.2.5012
vti_syncwith_www.coli.net\:80/lentic:TR|29 Jun 2004 12:26:39 -0000
vti_lineageid:SR|{4DD53656-B25E-4712-B2AF-0EBED8BD3605}
vti_cacheddtm:TX|15 Sep 2004 16:56:03 -0000
vti_filesize:IR|2054
vti_backlinkinfo:VX|
