<%
applicationurl="http://www.lentic.be/absoluteig/"
license="Lentic"
siteurl="http://www.lentic.be/"
adminusr="lentic"
adminpwd="ulg"
tnprefix="mini-"
gallerytitle="Technologie, innovation et changement"
rows=4
columns=3
newdays=30
displaydesc="checked"
disableclick=""
enablemybox="checked"
enablesend=""
streamdownload=""
defaultindexstatus="1"
defaultuploadstatus="0"
publicupload="1"
publicuploadblock=""
publicuploadsize="0"
displayhits=""
displayrating=""
myboxlimit=0
keeplog=""
logfile="email.txt"
disablemsg="Merci de respecter le droit d'auteur..."
downloadlink=""
imagecomponent="ASPJpeg"
flytn=""
tnsize="120"
savetn=""
defaultslidetime=8
postcardsubject=""
mailsignature=" "
mainsubject=""
mailadmin=""
smtpserver="webmail.activeisp.com"
kblimit=100000000
ieimagebar=""
mainmessage=" "
allowpostcards=""
pcsize=580
xla_id="2957114"

%>